### ISSUE TITLE
Socket is closed as soon as UdpListener goes out of scope

### ISSUE THREAD

**Issue by MatthewCash** [narrowlink/udp-stream#15]
Because the `impl Drop for UdpListener` stops the socket's connection handler, as soon as the `UdpListener` goes out of scope all of its connections are broken. This isn't a problem with `TcpListener` because each connection gets its own socket that is handled separately.

Here's a small example that shows fails with "Error: broken pipe" after 2 reads.

```rust
let mut stream = {
    let server = UdpListener::bind("0.0.0.0:9040".parse()?).await?;
    server.accept().await?.0
};
let mut buf = [0u8; 100];
loop {
    let n = stream.read(&mut buf).await?;
    println!("read {n} bytes");
}
```

**Comment by asuper0** [comment]
`UdpListener` is designed to act like a `TcpListener`, but UDP is quite differ from TCP. Every new TCP client from TcpListener.accept() is a new socket, while every UDP client shares one socket. So the `UdpStream` must rely on the `UdpListener`.

Suggest to use following

```rust
    let socket = UdpSocket::bind("0.0.0.0:9040").await?;
    let mut buf = vec![0u8; 32];
    let (len, addr) = socket.recv_from(&mut buf).await?;
    let mut stream = UdpStream::from_tokio(socket, addr).unwrap();
```

**Comment by MatthewCash** [comment]
Thank you! Starting with the tokio socket works and it can be dropped without breaking the socket.

I also wonder if there is a way to prevent the `UdpListener`'s handler from being stopped until the `streams` map is empty, that would probably fix the original issue, but using the tokio socket works great.
